#!/usr/bin/python
import RPi.GPIO as GPIO
import time

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)

#Traffic Light
GPIO.setup(17,GPIO.OUT)       #Red   Light
GPIO.setup(27,GPIO.OUT)       #Amber Light
GPIO.setup(22,GPIO.OUT)       #Green Light

#For Pedestrian
GPIO.setup(23,GPIO.OUT)       #Red   Light
GPIO.setup(24,GPIO.OUT)       #Green Light

#Button
GPIO.setup(25,GPIO.IN)        #Push Button 


while True:
    
    if GPIO.input(25):        #Button Pressed and Activate
        
        #State 2
        GPIO.output(22,True)  #Traffic Green Light on
        time.sleep(2)         #Delay 2 secs
        GPIO.output(22,False) #Traffic Green Light off
        
        GPIO.output(27,True)  #Traffic Amber Light on
        time.sleep(2)         #Delay 2 secs
        GPIO.output(27,False) #Traffic Amber Light off
        
        GPIO.output(17,True)  #Traffic Red Light on
        time.sleep(2)         #Delay 2 secs
        

        #State 3
        GPIO.output(23,False) #Pedes Red Light on
        GPIO.output(24,True)  #Pedes Green Light on
        time.sleep(5)         #Delay 2 secs
        
        #State 4
        
        for i in range(0,6):
            GPIO.output(24,True)  #Pedes Green Light Blink On
            time.sleep(0.5)         #Delay 1 secs
            GPIO.output(24,False)  #Pedes Green Light Blink On
            time.sleep(1)         #Delay 1 secs

    else:
        GPIO.output(17,False)  #Traffic Red Light off
        
        #State 1
        GPIO.output(22,True)  #Traffic Green Light on
        GPIO.output(23,True)  #Pedes   Red Light on
